/**
 * Export Service
 *
 * Core service for exporting assessment data in various formats.
 * Supports JSON, ZIP (with attachments), PDF, and CSV exports.
 */

import JSZip from 'jszip';

import { db } from '../db';
import { getDomainById, getAreaById } from '../capabilities';
import { calculateAverageScore, calculateDimensionScore } from '../scoring';
import { isEnterpriseDomain, getAggregatedDimensionForDomain } from '../orbit';
import { getAreasFromDomain } from '../../types';
import type {
  ExportOptions,
  ExportData,
  AttachmentMetadata,
  MaturityProfile,
  CapabilityAreaProfile,
  MaturityProfileRow,
  ExportProgressCallback,
  ExportEnterpriseAssessment,
} from './types';
import type {
  CapabilityAssessment,
  OrbitRating,
  AssessmentHistory,
  Tag,
  OrbitDimensionId,
} from '../../types';
import { generatePdfReport } from './pdfExport';
import { generateMaturityProfileCsv, generateCombinedMaturityProfileCsv } from './csvExport';

/** Current export format version */
const EXPORT_VERSION = '1.0';

/** App version injected at build time */
const APP_VERSION = __APP_VERSION__;

/**
 * Generates a unique filename for an attachment in the ZIP export.
 * Embeds the attachment ID to ensure uniqueness and enable reliable import matching.
 *
 * @param attachmentId - The unique ID of the attachment
 * @param originalFileName - The original filename uploaded by the user
 * @returns A unique filename in format: {baseName}_{attachmentId}.{extension}
 *
 * @example
 * generateUniqueExportFileName('abc-123', 'report.pdf')
 * // Returns: 'report_abc-123.pdf'
 */
function generateUniqueExportFileName(attachmentId: string, originalFileName: string): string {
  const lastDotIndex = originalFileName.lastIndexOf('.');
  if (lastDotIndex === -1) {
    // No extension
    return `${originalFileName}_${attachmentId}`;
  }
  const baseName = originalFileName.substring(0, lastDotIndex);
  const extension = originalFileName.substring(lastDotIndex + 1);
  return `${baseName}_${attachmentId}.${extension}`;
}

/**
 * Extracts the attachment ID from a unique export filename.
 *
 * @param uniqueFileName - The filename generated by generateUniqueExportFileName
 * @returns The attachment ID, or null if the filename doesn't match the expected format
 *
 * @example
 * extractAttachmentIdFromFileName('report_abc-123.pdf')
 * // Returns: 'abc-123'
 */
export function extractAttachmentIdFromFileName(uniqueFileName: string): string | null {
  // Pattern: {baseName}_{attachmentId}.{extension} or {baseName}_{attachmentId}
  const lastDotIndex = uniqueFileName.lastIndexOf('.');
  const nameWithoutExt =
    lastDotIndex === -1 ? uniqueFileName : uniqueFileName.substring(0, lastDotIndex);
  const lastUnderscoreIndex = nameWithoutExt.lastIndexOf('_');

  if (lastUnderscoreIndex === -1) {
    return null;
  }

  return nameWithoutExt.substring(lastUnderscoreIndex + 1);
}

/**
 * Collects all data for export based on scope
 */
async function collectExportData(options: ExportOptions): Promise<ExportData> {
  const { scope, domainId, areaId } = options;

  let assessments: CapabilityAssessment[] = [];
  let ratings: OrbitRating[] = [];
  let history: AssessmentHistory[] = [];
  let scopeDetails: ExportData['scopeDetails'];

  if (scope === 'area' && areaId) {
    // Single capability area
    const area = getAreaById(areaId);
    const assessment = await db.capabilityAssessments
      .where('capabilityAreaId')
      .equals(areaId)
      .first();

    if (assessment) {
      assessments = [assessment];
      ratings = await db.orbitRatings
        .where('capabilityAssessmentId')
        .equals(assessment.id)
        .toArray();
      history = await db.assessmentHistory.where('capabilityAreaId').equals(areaId).toArray();
    }

    scopeDetails = {
      areaId,
      areaName: area?.name,
      domainId: assessment?.capabilityDomainId,
      domainName: assessment?.capabilityDomainName,
    };
  } else if (scope === 'domain' && domainId) {
    // All areas in a domain
    const domain = getDomainById(domainId);
    if (domain) {
      const areas = getAreasFromDomain(domain);
      const areaIds = areas.map((a) => a.id);

      assessments = await db.capabilityAssessments
        .where('capabilityAreaId')
        .anyOf(areaIds)
        .toArray();

      const assessmentIds = assessments.map((a) => a.id);
      ratings = await db.orbitRatings
        .where('capabilityAssessmentId')
        .anyOf(assessmentIds)
        .toArray();

      history = await db.assessmentHistory.where('capabilityAreaId').anyOf(areaIds).toArray();

      scopeDetails = {
        domainId,
        domainName: domain.name,
      };
    }
  } else {
    // Full export
    assessments = await db.capabilityAssessments.toArray();
    ratings = await db.orbitRatings.toArray();
    history = await db.assessmentHistory.toArray();
  }

  // Get all tags
  const tags: Tag[] = await db.tags.toArray();

  // Get attachment metadata (not blobs)
  const assessmentIds = assessments.map((a) => a.id);
  const attachmentsRaw = await db.attachments
    .where('capabilityAssessmentId')
    .anyOf(assessmentIds)
    .toArray();

  const attachments: AttachmentMetadata[] = attachmentsRaw.map((a) => ({
    id: a.id,
    capabilityAssessmentId: a.capabilityAssessmentId,
    orbitRatingId: a.orbitRatingId,
    fileName: a.fileName,
    fileType: a.fileType,
    fileSize: a.fileSize,
    description: a.description,
    uploadedAt: a.uploadedAt.toISOString(),
  }));

  // Calculate aggregate data for enterprise domain assessments
  const enterpriseAggregates = await calculateEnterpriseAggregatesForExport(assessments, ratings);

  return {
    exportVersion: EXPORT_VERSION,
    exportDate: new Date().toISOString(),
    appVersion: APP_VERSION,
    scope,
    scopeDetails,
    data: {
      assessments,
      ratings,
      history,
      tags,
      attachments,
    },
    metadata: {
      totalAssessments: assessments.length,
      totalRatings: ratings.length,
      totalHistory: history.length,
      totalAttachments: attachments.length,
      capabilities: assessments.map((a) => `${a.capabilityDomainId}/${a.capabilityAreaId}`),
    },
    enterpriseAggregates: enterpriseAggregates.length > 0 ? enterpriseAggregates : undefined,
  };
}

/**
 * Calculate aggregate data for enterprise domain assessments in the export.
 * This captures the current aggregate scores for traceability.
 */
async function calculateEnterpriseAggregatesForExport(
  assessments: CapabilityAssessment[],
  allRatings: OrbitRating[]
): Promise<ExportEnterpriseAssessment[]> {
  const enterpriseAssessments = assessments.filter(
    (a) => a.status === 'finalized' && isEnterpriseDomain(a.capabilityDomainId)
  );

  if (enterpriseAssessments.length === 0) {
    return [];
  }

  // Get all finalized non-enterprise assessments for aggregate calculation
  const qualifyingAssessments = assessments.filter(
    (a) => a.status === 'finalized' && !isEnterpriseDomain(a.capabilityDomainId)
  );

  // Group ratings by assessment
  const ratingsByAssessment = new Map<string, OrbitRating[]>();
  for (const rating of allRatings) {
    const existing = ratingsByAssessment.get(rating.capabilityAssessmentId) ?? [];
    existing.push(rating);
    ratingsByAssessment.set(rating.capabilityAssessmentId, existing);
  }

  const results: ExportEnterpriseAssessment[] = [];

  for (const assessment of enterpriseAssessments) {
    const aggregatedDimension = getAggregatedDimensionForDomain(assessment.capabilityDomainId);
    if (!aggregatedDimension) continue;

    // Calculate aggregate score
    const aggregateResult = calculateAggregateDimensionScoreForExport(
      aggregatedDimension,
      qualifyingAssessments,
      ratingsByAssessment
    );

    results.push({
      assessmentId: assessment.id,
      domainId: assessment.capabilityDomainId,
      domainName: assessment.capabilityDomainName,
      aggregateData: {
        dimensionId: aggregatedDimension,
        score: aggregateResult.score,
        contributingCount: aggregateResult.contributingCount,
        contributingAssessmentIds: aggregateResult.assessmentIds,
      },
    });
  }

  return results;
}

/**
 * Calculate aggregate dimension score for export.
 */
function calculateAggregateDimensionScoreForExport(
  dimensionId: OrbitDimensionId,
  qualifyingAssessments: CapabilityAssessment[],
  ratingsByAssessment: Map<string, OrbitRating[]>
): { score: number | null; contributingCount: number; assessmentIds: string[] } {
  const scoresWithIds: { id: string; score: number }[] = [];

  for (const assessment of qualifyingAssessments) {
    const ratings = ratingsByAssessment.get(assessment.id) ?? [];
    const dimRatings = ratings.filter((r) => r.dimensionId === dimensionId);

    const dimScore = calculateDimensionScore(dimensionId, dimRatings);
    if (dimScore !== null) {
      scoresWithIds.push({ id: assessment.id, score: dimScore });
    }
  }

  if (scoresWithIds.length === 0) {
    return { score: null, contributingCount: 0, assessmentIds: [] };
  }

  const avgScore = scoresWithIds.reduce((sum, s) => sum + s.score, 0) / scoresWithIds.length;
  return {
    score: Math.round(avgScore * 10) / 10,
    contributingCount: scoresWithIds.length,
    assessmentIds: scoresWithIds.map((s) => s.id),
  };
}

/**
 * Exports data as JSON string
 */
export async function exportAsJson(options: ExportOptions): Promise<string> {
  const data = await collectExportData(options);
  return JSON.stringify(data, null, 2);
}

/**
 * Exports data as a ZIP file containing JSON, CSV profiles, and attachments
 */
export async function exportAsZip(
  options: ExportOptions,
  onProgress?: ExportProgressCallback
): Promise<Blob> {
  const zip = new JSZip();

  onProgress?.(10, 'Collecting assessment data...');

  // Collect export data
  const exportData = await collectExportData(options);

  onProgress?.(30, 'Adding JSON data...');

  // Add JSON data file
  zip.file('data.json', JSON.stringify(exportData, null, 2));

  onProgress?.(40, 'Generating CSV maturity profiles...');

  // Add CSV maturity profiles
  const csvFolder = zip.folder('maturity-profiles');
  if (csvFolder) {
    const profiles = await generateAllMaturityProfiles(options);

    // Add individual domain CSVs
    for (const profile of profiles) {
      const csv = generateMaturityProfileCsv(profile);
      const fileName = `${profile.domainName.toLowerCase().replace(/\s+/g, '-')}-maturity-profile.csv`;
      csvFolder.file(fileName, csv);
    }

    // Add combined CSV with all domains
    if (profiles.length > 0) {
      const combinedCsv = generateCombinedMaturityProfileCsv(
        profiles,
        options.stateName ?? 'State'
      );
      csvFolder.file('all-domains-maturity-profile.csv', combinedCsv);
    }
  }

  onProgress?.(60, 'Adding attachments...');

  // Add attachments if requested
  if (options.includeAttachments !== false) {
    const attachmentsFolder = zip.folder('attachments');
    if (attachmentsFolder) {
      const assessmentIds = exportData.data.assessments.map((a) => a.id);
      const attachments = await db.attachments
        .where('capabilityAssessmentId')
        .anyOf(assessmentIds)
        .toArray();

      for (const attachment of attachments) {
        // Find the assessment for folder structure
        const assessment = exportData.data.assessments.find(
          (a) => a.id === attachment.capabilityAssessmentId
        );
        if (assessment) {
          const folderPath = `${assessment.capabilityDomainId}/${assessment.capabilityAreaId}`;
          const folder = attachmentsFolder.folder(folderPath);
          // Use unique filename to prevent overwrites when multiple attachments have same name
          const uniqueFileName = generateUniqueExportFileName(attachment.id, attachment.fileName);
          folder?.file(uniqueFileName, attachment.blob);
        }
      }
    }
  }

  onProgress?.(80, 'Creating manifest...');

  // Add manifest
  const manifest = {
    exportVersion: EXPORT_VERSION,
    exportDate: exportData.exportDate,
    appVersion: APP_VERSION,
    scope: options.scope,
    contents: {
      dataJson: true,
      maturityProfiles: true,
      attachments: options.includeAttachments !== false,
    },
    stats: exportData.metadata,
  };
  zip.file('manifest.json', JSON.stringify(manifest, null, 2));

  onProgress?.(90, 'Compressing...');

  // Generate ZIP blob
  const blob = await zip.generateAsync({ type: 'blob', compression: 'DEFLATE' });

  onProgress?.(100, 'Complete');

  return blob;
}

/**
 * Generates maturity profiles for all domains in scope
 */
async function generateAllMaturityProfiles(options: ExportOptions): Promise<MaturityProfile[]> {
  const profiles: MaturityProfile[] = [];
  const stateName = options.stateName ?? 'State';

  if (options.scope === 'area' && options.areaId) {
    // Single area - get its domain
    const assessment = await db.capabilityAssessments
      .where('capabilityAreaId')
      .equals(options.areaId)
      .first();

    if (assessment) {
      const profile = await generateDomainMaturityProfile(assessment.capabilityDomainId, stateName);
      if (profile) profiles.push(profile);
    }
  } else if (options.scope === 'domain' && options.domainId) {
    // Single domain
    const profile = await generateDomainMaturityProfile(options.domainId, stateName);
    if (profile) profiles.push(profile);
  } else {
    // Full export - all domains with assessments
    const assessments = await db.capabilityAssessments.toArray();
    const domainIds = [...new Set(assessments.map((a) => a.capabilityDomainId))];

    for (const domainId of domainIds) {
      const profile = await generateDomainMaturityProfile(domainId, stateName);
      if (profile) profiles.push(profile);
    }
  }

  return profiles;
}

/**
 * Generates a maturity profile for a single domain
 * Creates a profile with sections for each capability area
 */
async function generateDomainMaturityProfile(
  domainId: string,
  stateName: string
): Promise<MaturityProfile | null> {
  const domain = getDomainById(domainId);
  if (!domain) return null;

  const areas = getAreasFromDomain(domain);
  const areaIds = areas.map((a) => a.id);

  // Get all finalized assessments for this domain
  const assessments = await db.capabilityAssessments
    .where('capabilityAreaId')
    .anyOf(areaIds)
    .and((a) => a.status === 'finalized')
    .toArray();

  if (assessments.length === 0) return null;

  // Get all ratings for these assessments
  const assessmentIds = assessments.map((a) => a.id);
  const allRatings = await db.orbitRatings
    .where('capabilityAssessmentId')
    .anyOf(assessmentIds)
    .toArray();

  // Check if this is an enterprise domain and calculate aggregate if needed
  const aggregatedDimension = getAggregatedDimensionForDomain(domainId);
  let aggregateData:
    | { dimensionId: OrbitDimensionId; score: number | null; contributingCount: number }
    | undefined;

  if (aggregatedDimension) {
    // Get all finalized non-enterprise assessments for aggregate calculation
    const allAssessments = await db.capabilityAssessments.toArray();
    const qualifyingAssessments = allAssessments.filter(
      (a) => a.status === 'finalized' && !isEnterpriseDomain(a.capabilityDomainId)
    );

    const qualifyingIds = qualifyingAssessments.map((a) => a.id);
    const qualifyingRatings = await db.orbitRatings
      .where('capabilityAssessmentId')
      .anyOf(qualifyingIds)
      .toArray();

    // Group ratings by assessment
    const ratingsByAssessment = new Map<string, OrbitRating[]>();
    for (const rating of qualifyingRatings) {
      const existing = ratingsByAssessment.get(rating.capabilityAssessmentId) ?? [];
      existing.push(rating);
      ratingsByAssessment.set(rating.capabilityAssessmentId, existing);
    }

    const result = calculateAggregateDimensionScoreForExport(
      aggregatedDimension,
      qualifyingAssessments,
      ratingsByAssessment
    );

    aggregateData = {
      dimensionId: aggregatedDimension,
      score: result.score,
      contributingCount: result.contributingCount,
    };
  }

  // Build capability area profiles
  const areaProfiles: CapabilityAreaProfile[] = [];

  for (const assessment of assessments) {
    const areaRatings = allRatings.filter((r) => r.capabilityAssessmentId === assessment.id);
    const areaProfile = generateCapabilityAreaProfile(assessment, areaRatings, aggregateData);
    areaProfiles.push(areaProfile);
  }

  return {
    stateName,
    domainName: domain.name,
    areas: areaProfiles,
  };
}

/**
 * Generates a profile for a single capability area.
 * For enterprise domains, includes aggregate dimension data with indicator.
 *
 * @param assessment - The capability assessment
 * @param ratings - Ratings for this assessment
 * @param aggregateData - Optional aggregate data for enterprise domains
 */
function generateCapabilityAreaProfile(
  assessment: CapabilityAssessment,
  ratings: OrbitRating[],
  aggregateData?: { dimensionId: OrbitDimensionId; score: number | null; contributingCount: number }
): CapabilityAreaProfile {
  // Map dimension IDs to display names (matches MITA 4.0 ORBIT model)
  const dimensionMap: Record<OrbitDimensionId, string> = {
    outcomes: 'Outcomes',
    roles: 'Roles',
    businessArchitecture: 'Business Architecture',
    information: 'Information',
    technology: 'Technology',
  };

  // Group ratings by dimension and calculate averages
  const dimensionData: Record<
    string,
    {
      asIs: number[];
      toBe: number[];
      notes: string[];
      barriers: string[];
      plans: string[];
    }
  > = {};

  // Initialize all dimensions
  for (const dimName of Object.values(dimensionMap)) {
    dimensionData[dimName] = {
      asIs: [],
      toBe: [],
      notes: [],
      barriers: [],
      plans: [],
    };
  }

  // Aggregate data from ratings
  for (const rating of ratings) {
    const dimName = dimensionMap[rating.dimensionId];
    if (!dimName) continue;

    const dimData = dimensionData[dimName];
    if (!dimData) continue;

    // Collect scores (only positive values)
    if (rating.currentLevel > 0) {
      dimData.asIs.push(rating.currentLevel);
    }
    if (rating.targetLevel && rating.targetLevel > 0) {
      dimData.toBe.push(rating.targetLevel);
    }

    // Collect text fields (non-empty only)
    if (rating.notes && rating.notes.trim()) {
      dimData.notes.push(rating.notes.trim());
    }
    if (rating.barriers && rating.barriers.trim()) {
      dimData.barriers.push(rating.barriers.trim());
    }
    if (rating.plans && rating.plans.trim()) {
      dimData.plans.push(rating.plans.trim());
    }
  }

  // Build rows for each dimension
  const rows: MaturityProfileRow[] = [];

  for (const [dimId, dimName] of Object.entries(dimensionMap)) {
    const dimData = dimensionData[dimName];
    if (!dimData) continue;

    // Check if this is an aggregate dimension for this assessment
    const isAggregate = aggregateData?.dimensionId === dimId;

    let asIsAvg: string;
    let toBeAvg: string;
    let notes: string;

    if (isAggregate && aggregateData) {
      // Use aggregate score for enterprise domains
      asIsAvg = aggregateData.score !== null ? aggregateData.score.toFixed(1) : '';
      toBeAvg = ''; // Aggregate doesn't have target level
      notes = `(Aggregate from ${aggregateData.contributingCount} assessments)`;
    } else {
      // Calculate averages using shared scoring utility
      const asIsScore = calculateAverageScore(dimData.asIs);
      const toBeScore = calculateAverageScore(dimData.toBe);
      asIsAvg = asIsScore !== null ? asIsScore.toFixed(1) : '';
      toBeAvg = toBeScore !== null ? toBeScore.toFixed(1) : '';
      notes = dimData.notes.join('; ');
    }

    // Combine text fields (join multiple entries with semicolon)
    const barriers = dimData.barriers.join('; ');
    const plans = dimData.plans.join('; ');

    rows.push({
      dimension: dimName,
      asIs: asIsAvg,
      toBe: toBeAvg,
      notes,
      barriers,
      plans,
    });
  }

  return {
    domainName: assessment.capabilityDomainName,
    areaName: assessment.capabilityAreaName,
    rows,
  };
}

/**
 * Exports data as PDF report
 */
export async function exportAsPdf(
  options: ExportOptions,
  onProgress?: ExportProgressCallback
): Promise<Blob> {
  onProgress?.(10, 'Collecting data...');
  const exportData = await collectExportData(options);

  onProgress?.(50, 'Generating PDF...');
  const blob = await generatePdfReport(exportData, options);

  onProgress?.(100, 'Complete');
  return blob;
}

/**
 * Exports a single domain's maturity profile as CSV
 */
export async function exportDomainCsv(
  domainId: string,
  stateName: string = 'State'
): Promise<string | null> {
  const profile = await generateDomainMaturityProfile(domainId, stateName);
  if (!profile) return null;
  return generateMaturityProfileCsv(profile);
}

/**
 * Exports all domains' maturity profiles as a single combined CSV
 */
export async function exportAllDomainsCsv(stateName: string = 'State'): Promise<string | null> {
  const profiles = await generateAllMaturityProfiles({ scope: 'full', format: 'csv', stateName });
  if (profiles.length === 0) return null;
  return generateCombinedMaturityProfileCsv(profiles, stateName);
}

/**
 * Downloads a blob as a file
 */
export function downloadBlob(blob: Blob, filename: string): void {
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

/**
 * Downloads text as a file
 */
export function downloadText(text: string, filename: string, mimeType: string): void {
  const blob = new Blob([text], { type: mimeType });
  downloadBlob(blob, filename);
}

/**
 * Generates a filename with timestamp
 */
export function generateFilename(prefix: string, extension: string, scope?: string): string {
  const date = new Date().toISOString().split('T')[0];
  const scopePart = scope ? `-${scope}` : '';
  return `mita-${prefix}${scopePart}-${date}.${extension}`;
}
